CREATE TABLE IF NOT EXISTS USERS (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(56) UNIQUE,
    EMAIL VARCHAR(265) NOT NULL UNIQUE,
    PASSWORD VARCHAR(128) NOT NULL,
    FIRST_NAME VARCHAR(90),
    LAST_NAME VARCHAR(250),
    IS_ADMIN BOOL NOT NULL DEFAULT FALSE,
    JOINED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
