-- SQL Migration 2021-01-27T11.44.45.135429600 employeetable
-- Employees of the system

CREATE TABLE IF NOT EXISTS EMPLOYEES(
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL UNIQUE,
    EMPLOYEE_EMAIL VARCHAR(256) NOT NULL UNIQUE,
    INITIALS VARCHAR(6) NOT NULL UNIQUE,
    WORK_PHONE VARCHAR(12),

    -- Foreign keys
    CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
)
